/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Rectangle1Image from '../images/JFJHB_thumbnail.jpg';
import Rectangle2Image from '../images/MZHB_thumbnail.jpg';
import Rectangle3Image from '../images/RMHB_thumbnail.jpg';
import styled from 'styled-components';




function Homepage(props) {
  return (
    <div className="HomepageCanvas">
      <div className="HomepageFrame">
        <div className="HomepageTileTextBackground">Magazine Gallery</div>
        <div className="HomepageMazineContainer">
          <div className="HomepageMagazine">
            <a href="http://localhost:3000/Gallery/JFJHB">
              <img className="HomepageMagazineCover" src={Rectangle1Image} loading="lazy" alt="Rectangle 1" />
            </a>
            <div className="HomepageMagazineTitle">解放军画报</div>
            <div className="HomepageMagazineInfo">
              解放军画报于1951年2月创刊，由毛泽东主席亲笔题写刊名。其前身是红军时期的《红星画报》、抗日战争时期的《晋察冀画报》和解放战争时期的《华北画报》。邓小平、江泽民多次接受本刊记者采访拍摄。
            </div>
          </div>
          <div className="HomepageMagazine">
            <a href="http://localhost:3000/Gallery/RMHB">
              <img className="HomepageMagazineCover" src={Rectangle3Image} loading="lazy" alt="Rectangle 3" />
            </a>
            <div className="HomepageMagazineTitle">人民画报</div>
            <div className="HomepageMagazineInfo">
              《人民画报》创刊于1950年7月，是一本以图片报道为主、图文并茂的中华人民共和国国家级综合性画报，为月刊，内容以宣传中国现代建设成就为主。《人民画报》自创办起从未停刊，文化大革命中也照常出版。
            </div>
          </div>
          <div className="HomepageMagazine">
            <a href="http://localhost:3000/Gallery/MZHB">
              <img className="HomepageMagazineCover" src={Rectangle2Image} loading="lazy" alt="Rectangle 2" />  
            </a>

            <div className="HomepageMagazineTitle">民族画报</div>
            <div className="HomepageMagazineInfo">
              民族画报创刊于1956年12月份。作为中国第一本以民族为主题的大型刊物，它致力于展示和传承中国各民族的文化遗产、艺术表达和社会风貌，广泛涵盖了中国各个民族的风土人情、历史传统、习俗民俗、服饰饮食、音乐舞蹈、手工艺等方面。
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
export default Homepage;
